---
- name: importing common file
  import_playbook: ../static-assignments/common.yml
  tags:
    - always


- name: Include dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: import db files
  import_playbook: ../static-assignments/db.yml


- name: Import webserver assignment 
  import_playbook: ../static-assignments/webservers.yml

- name: Loadbalancers assignment

- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 
   
         
